// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/[name].tsx';
import * as $1 from './routes/_render.ts';
import * as $2 from './routes/api/joke.ts';
import * as $3 from './routes/index.css.ts';
import * as $4 from './routes/index.tsx';

const manifest = {
  routes: {
    './routes/[name].tsx': $0,
    './routes/_render.ts': $1,
    './routes/api/joke.ts': $2,
    './routes/index.css.ts': $3,
    './routes/index.tsx': $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
