name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          deno-version: v1.*

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Check formatting
        run: deno fmt

      - name: Lint
        run: deno lint

      - name: Typecheck
        run: deno check src/main.js